server:
  port: 8010
spring:
  application:
    name: orange-zuul
  cloud:
    cousul:
      host: localhost
      port: 8500
      discovery:
        serviceName: ${spring.application.name}
zuul:
  routes:
    ribbon:
      path: /ribbon/**
      serviceId: orange-consumer
    feign:
      path: /feign/**
      serviceId: orange-consumer
