server:
  port: 8501
spring:
  application:
    name: orange-hystrix
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        serviceName: ${spring.application.name}  #注册到consul的服务名称
turbine:
  instanceUrlSuffix: hystrix.stream     #指定搜集路径
  app-config: orange-consumer  #指定了需要手机监控信息的服务名，多个以“，”进行区分
  cluster-name-expression: "'default'"
  #指定集群名称，若为default则为默认集群，多个集群则通过此配置区分
  combine-host-port: true
  #默认为false，服务以host进行区分，若设置为true则以host+port进行区分