server:
  port: 8220
spring:
  application:
    name: orange-gateway
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        serviceName: ${spring.application.name}
        health-check-path: /actuator/health
        health-check-interval: 10s
    gateway:
      default-filters:
        name: Hystrix
        args:
          name: fallbackcmd
          fallbackUri: forward:/fallback
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
#      routes:
#      - id: orange-consumer
#        uri: http://localhost:8005
#        predicates:
#        - Path=/orange-consumer/**
feign:
  hystrix:
    enabled: true



